[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.websocket"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "websocket-server"

[services.variables]
NODE_ENV = "production"
PORT = "3001"
